# Copyright 2020 Wayback Archiver. All rights reserved.
# Use of this source code is governed by the MIT license
# that can be found in the LICENSE file.

name: Linter

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    types: [ opened, synchronize, reopened ]
  workflow_call:

permissions:
  contents: read

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v2.0.0
        with:
          disable-sudo: true
          egress-policy: block
          disable-telemetry: true
          allowed-endpoints: >
            github.com:443
            api.github.com:443

      - name: Check out code base
        if: github.event_name == 'push'
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check out code base
        if: github.event_name == 'pull_request'
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Lint Code Base
        uses: github/super-linter@bb2d833b08b6c288608686672b93a8a4589cdc49 # v4.9.7
        env:
          DEFAULT_BRANCH: 'main'
          VALIDATE_MARKDOWN: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

