# Copyright 2020 Wayback Archiver. All rights reserved.
# Use of this source code is governed by the MIT license
# that can be found in the LICENSE file.

name: Debian Package Builder

on:
  workflow_call:
    inputs:
      product:
        type: string
        required: true
        description: 'Product or package name'
      go-arch:
        type: string
        default: 'amd64'
        description: 'Golang version, defaults to amd64'
      go-arm:
        type: string
        description: 'Golang arm environment'
      artifact-path:
        type: string
        required: true
        description: 'Path to stores artifacts.'
      egress-policy:
        type: string
        default: 'block'
        description: 'Harden-Runner egress traffic policy'
    secrets:
      wayback-ipfs-target:
        description: 'Managed IPFS target for distribution binaries.'
      wayback-ipfs-apikey:
        description: 'Managed IPFS credential for distribution binaries.'
      wayback-ipfs-secret:
        description: 'Managed IPFS secret for distribution binaries.'

permissions:
  contents: read

jobs:
  debian-builder:
    name: Debian Package Builder
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          disable-sudo: true
          egress-policy: ${{ inputs.egress-policy || 'block' }}
          disable-telemetry: true
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            deb.debian.org:443
            deb.debian.org:80
            docker.io:443
            auth.docker.io:443
            registry-1.docker.io:443
            production.cloudflare.docker.com:443
            storage.googleapis.com:443
            proxy.golang.org:443
            sum.golang.org:443

      - name: Check out code base
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check out code base
        if: github.event_name == 'pull_request'
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
        id: buildx
        with:
          install: true

      - name: Available Docker Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build Debian package
        id: builder
        env:
          WAYBACK_IPFS_TARGET: ${{ secrets.wayback-ipfs-target }}
          WAYBACK_IPFS_APIKEY: ${{ secrets.wayback-ipfs-apikey }}
          WAYBACK_IPFS_SECRET: ${{ secrets.wayback-ipfs-secret }}
          GOARCH: ${{ inputs.go-arch }}
          GOARM: ${{ inputs.go-arm }}
        run: |
          TARGET="${GOARCH}"
          if [[ -n "${GOARM}" ]]; then
            TARGET="${GOARCH}/v${GOARM}"
          fi
          PKG_ARCH="${TARGET//\/v8}"
          PKG_ARCH="${PKG_ARCH//32}"
          echo "DOCKER_PLATFORM: ${PKG_ARCH}"
          make debian DOCKER_PLATFORM=${PKG_ARCH}
          echo "filename=${{ inputs.product }}-deb-${PKG_ARCH//\/}" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: ${{ steps.builder.outputs.filename }}
          path: ${{ inputs.artifact-path }}
          if-no-files-found: error
